/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface EventSection {
        "headline": string;
        "subtitle": string;
        "variant"?: 'primary' | 'secondary' | 'tertiary' | 'default';
    }
    interface HeaderImage {
        "headline": string;
        "image": string;
        "subheader": string;
    }
    interface StackLayout {
        "overlap": number;
    }
    interface StackSection {
        "headline": string;
        "subtitle": string;
        "variant"?: 'primary' | 'secondary' | 'tertiary' | 'default';
    }
}
declare global {
    interface HTMLEventSectionElement extends Components.EventSection, HTMLStencilElement {
    }
    var HTMLEventSectionElement: {
        prototype: HTMLEventSectionElement;
        new (): HTMLEventSectionElement;
    };
    interface HTMLHeaderImageElement extends Components.HeaderImage, HTMLStencilElement {
    }
    var HTMLHeaderImageElement: {
        prototype: HTMLHeaderImageElement;
        new (): HTMLHeaderImageElement;
    };
    interface HTMLStackLayoutElement extends Components.StackLayout, HTMLStencilElement {
    }
    var HTMLStackLayoutElement: {
        prototype: HTMLStackLayoutElement;
        new (): HTMLStackLayoutElement;
    };
    interface HTMLStackSectionElement extends Components.StackSection, HTMLStencilElement {
    }
    var HTMLStackSectionElement: {
        prototype: HTMLStackSectionElement;
        new (): HTMLStackSectionElement;
    };
    interface HTMLElementTagNameMap {
        "event-section": HTMLEventSectionElement;
        "header-image": HTMLHeaderImageElement;
        "stack-layout": HTMLStackLayoutElement;
        "stack-section": HTMLStackSectionElement;
    }
}
declare namespace LocalJSX {
    interface EventSection {
        "headline"?: string;
        "subtitle"?: string;
        "variant"?: 'primary' | 'secondary' | 'tertiary' | 'default';
    }
    interface HeaderImage {
        "headline"?: string;
        "image"?: string;
        "subheader"?: string;
    }
    interface StackLayout {
        "overlap"?: number;
    }
    interface StackSection {
        "headline"?: string;
        "subtitle"?: string;
        "variant"?: 'primary' | 'secondary' | 'tertiary' | 'default';
    }
    interface IntrinsicElements {
        "event-section": EventSection;
        "header-image": HeaderImage;
        "stack-layout": StackLayout;
        "stack-section": StackSection;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "event-section": LocalJSX.EventSection & JSXBase.HTMLAttributes<HTMLEventSectionElement>;
            "header-image": LocalJSX.HeaderImage & JSXBase.HTMLAttributes<HTMLHeaderImageElement>;
            "stack-layout": LocalJSX.StackLayout & JSXBase.HTMLAttributes<HTMLStackLayoutElement>;
            "stack-section": LocalJSX.StackSection & JSXBase.HTMLAttributes<HTMLStackSectionElement>;
        }
    }
}
