/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface HeaderImage {
        "headline": string;
        "image": string;
        "subheader": string;
    }
    interface StackLayout {
        "overlap": number;
    }
    interface StackSection {
        "headline": string;
        "subtitle": string;
        "variant"?: 'primary' | 'secondary' | 'tertiary' | 'surface' | 'surface-variant';
    }
    interface StackSectionBlockImage {
        "url": string;
    }
}
declare global {
    interface HTMLHeaderImageElement extends Components.HeaderImage, HTMLStencilElement {
    }
    var HTMLHeaderImageElement: {
        prototype: HTMLHeaderImageElement;
        new (): HTMLHeaderImageElement;
    };
    interface HTMLStackLayoutElement extends Components.StackLayout, HTMLStencilElement {
    }
    var HTMLStackLayoutElement: {
        prototype: HTMLStackLayoutElement;
        new (): HTMLStackLayoutElement;
    };
    interface HTMLStackSectionElement extends Components.StackSection, HTMLStencilElement {
    }
    var HTMLStackSectionElement: {
        prototype: HTMLStackSectionElement;
        new (): HTMLStackSectionElement;
    };
    interface HTMLStackSectionBlockImageElement extends Components.StackSectionBlockImage, HTMLStencilElement {
    }
    var HTMLStackSectionBlockImageElement: {
        prototype: HTMLStackSectionBlockImageElement;
        new (): HTMLStackSectionBlockImageElement;
    };
    interface HTMLElementTagNameMap {
        "header-image": HTMLHeaderImageElement;
        "stack-layout": HTMLStackLayoutElement;
        "stack-section": HTMLStackSectionElement;
        "stack-section-block-image": HTMLStackSectionBlockImageElement;
    }
}
declare namespace LocalJSX {
    interface HeaderImage {
        "headline"?: string;
        "image"?: string;
        "subheader"?: string;
    }
    interface StackLayout {
        "overlap"?: number;
    }
    interface StackSection {
        "headline"?: string;
        "subtitle"?: string;
        "variant"?: 'primary' | 'secondary' | 'tertiary' | 'surface' | 'surface-variant';
    }
    interface StackSectionBlockImage {
        "url"?: string;
    }
    interface IntrinsicElements {
        "header-image": HeaderImage;
        "stack-layout": StackLayout;
        "stack-section": StackSection;
        "stack-section-block-image": StackSectionBlockImage;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "header-image": LocalJSX.HeaderImage & JSXBase.HTMLAttributes<HTMLHeaderImageElement>;
            "stack-layout": LocalJSX.StackLayout & JSXBase.HTMLAttributes<HTMLStackLayoutElement>;
            "stack-section": LocalJSX.StackSection & JSXBase.HTMLAttributes<HTMLStackSectionElement>;
            "stack-section-block-image": LocalJSX.StackSectionBlockImage & JSXBase.HTMLAttributes<HTMLStackSectionBlockImageElement>;
        }
    }
}
